server:
  port: 9411

  ##storage 配置 elasticsearch mysql 等
zipkin:
   storage:
      type: elasticsearch
      elasticsearch :
          host : 127.0.0.1:9200
          cluster: elasticsearch
          index: zipkin
          index-shards: 5
          index-replicas: 1

spring:
  sleuth:
    enabled: false
