spring:
  profiles:
    active: local
  datasource:
    schema: classpath:/zipkin.sql
    url: jdbc:mysql://127.0.0.1:3306/zipkin3
    username: root
    password: root
# Switch this on to create the schema on startup:
    initialize: true
    continueOnError: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

zipkin:
  storage:
    type: mysql

server:
  port: 9411
